apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: delta-frontend
  namespace: delta
  labels:
    team: delta
spec:
  image: {{image}}
  ingresses:
    - https://delta.intern.dev.nav.no
  port: 3000
